"""Added new widget tables

Revision ID: 6732f857b82b
Revises: 6a223fe75fd6
Create Date: 2025-06-04 01:52:51.229588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6732f857b82b'
down_revision: Union[str, None] = '6a223fe75fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_name', sa.String(length=255), nullable=False),
    sa.Column('widget_url', sa.String(length=255), nullable=False),
    sa.Column('widget_fields', sa.JSON(), nullable=False),
    sa.Column('widget_api_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_name')
    )
    op.create_table('widget_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('widget_value_key', sa.String(length=255), nullable=False),
    sa.Column('widget_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service_entry', sa.Column('widget_id', sa.Integer(), nullable=True))
    op.drop_column('service_entry', 'widget_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_entry', sa.Column('widget_key', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('service_entry', 'widget_id')
    op.drop_table('widget_value')
    op.drop_table('widget')
    # ### end Alembic commands ###
