"""Add widget_key to ServiceEntry

Revision ID: 6a223fe75fd6
Revises: f6f6681eb5d8
Create Date: 2025-06-04 01:19:16.298002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a223fe75fd6'
down_revision: Union[str, None] = 'f6f6681eb5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_entry', sa.Column('widget_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_entry', 'widget_key')
    # ### end Alembic commands ###
