"""Initial schema for v0.4.9 must backup and restore

Revision ID: 958ede516216
Revises: 
Create Date: 2025-06-22 01:03:23.394228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958ede516216'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_sort_priority', sa.Integer(), nullable=True),
    sa.Column('group_icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_name', sa.String(length=255), nullable=False),
    sa.Column('widget_url', sa.String(length=255), nullable=False),
    sa.Column('widget_fields', sa.JSON(), nullable=False),
    sa.Column('widget_api_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('container_name', sa.String(length=100), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('internalurl', sa.String(length=255), nullable=True),
    sa.Column('externalurl', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_api_update', sa.DateTime(), nullable=True),
    sa.Column('stack_name', sa.String(length=100), nullable=True),
    sa.Column('docker_status', sa.String(length=100), nullable=True),
    sa.Column('internal_health_check_enabled', sa.Boolean(), nullable=True),
    sa.Column('internal_health_check_status', sa.String(length=100), nullable=True),
    sa.Column('internal_health_check_update', sa.String(length=100), nullable=True),
    sa.Column('external_health_check_enabled', sa.Boolean(), nullable=True),
    sa.Column('external_health_check_status', sa.String(length=100), nullable=True),
    sa.Column('external_health_check_update', sa.String(length=100), nullable=True),
    sa.Column('image_registry', sa.String(length=100), nullable=True),
    sa.Column('image_owner', sa.String(length=100), nullable=True),
    sa.Column('image_name', sa.String(length=100), nullable=True),
    sa.Column('image_tag', sa.String(length=100), nullable=True),
    sa.Column('image_icon', sa.String(length=100), nullable=True),
    sa.Column('is_static', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.String(length=100), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('sort_priority', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('widget_value_key', sa.String(length=255), nullable=False),
    sa.Column('widget_value', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_value')
    op.drop_table('service_entry')
    op.drop_table('widget')
    op.drop_table('group')
    # ### end Alembic commands ###
