"""Add sort priority column

Revision ID: b6eef1708eeb
Revises: 1c4b532947e1
Create Date: 2025-06-21 17:58:34.452413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eef1708eeb'
down_revision: Union[str, None] = '1c4b532947e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_entry', sa.Column('sort_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_entry', 'sort_priority')
    # ### end Alembic commands ###
